import type { LeaderStock } from "~/app/(landing)/(index)/columns";
import { USER_STATUS } from "./const";

export const userStatus = USER_STATUS.NO_AUTH;

export const data: LeaderStock[] = [
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
  {
    symbol: "test",
    currentPrice: "test",
    recommendedDate: "test",
    marketCap: "test",
    recommendedPrice: "test",
    returnSinceRec: "test",
    returnVsSp500: "test",
    risk: "test",
    sP500ReturnsSince: "test",
    closeOpen: "test",
    closingPrice: "test",
    closedDate: "test",
  },
];
